version: '3.9'
services:
  mysql:
    image: mysql:8.0.34-debian
    environment:
      MYSQL_USER: tattoodb
      MYSQL_PASSWORD: ArtTattoo@@
      MYSQL_DB: tattoodb
      MYSQL_ROOT_PASSWORD: ArtTattoo@@
      PGDATA: /data/mysql
    ports:
      - 3306:3306
    networks:
      - app-network
    restart: always

  cache:
    image: redis:7.0-alpine
    environment:
      - REDIS_PASSWORD=ArtTattooRedis
    ports:
      - 6379:6379
    restart: always
    networks:
      - app-network

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DatabaseConnection=Server=mysql;Database=tattoodb;User=root;Password=ArtTattoo@@;
      - ConnectionStrings__RedisConnection=cache:6379,password=ArtTattooRedis,abortConnect=false
      - APP_VERSION=2.0.0
      - JWT_SECRET=ArtTattooSecret@@
      - SMTP_EMAIL=arttattoolover@gmail.com
      - SMTP_PASSWORD=zoxeglocinfzmnei
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - mysql
      - cache
    networks:
      - app-network

networks:
  app-network: