version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
      SA_PASSWORD: "ArtTattoo@@"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    networks:
      - app-network

  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DatabaseConnection=Server=db;Database=tattoodb;User=sa;Password=ArtTattoo@@;
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
    networks:
      - app-network


networks:
  app-network: