version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
      SA_PASSWORD: "ArtTattoo@@"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Evaluation"
    ports:
      - 1433:1433
    networks:
      - app-network

  cache:
    image: redis:7.0-alpine
    environment:
      - REDIS_PASSWORD=ArtTattooRedis
    ports:
      - 6379:6379
    restart: always
    networks:
      - app-network

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DatabaseConnection=Server=sqlserver;Database=tattoodb;User=sa;Password=ArtTattoo@@;MultipleActiveResultSets=true;TrustServerCertificate=true;
      - ConnectionStrings__RedisConnection=cache:6379,password=ArtTattooRedis,abortConnect=false
      - APP_VERSION=0.1.0
      - JWT_SECRET=ArtTattooSecret@@
      - SMTP_EMAIL=arttattoolover@gmail.com
      - SMTP_PASSWORD=zoxeglocinfzmnei
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - sqlserver
      - cache
    networks:
      - app-network

networks:
  app-network: